# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blockchain.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10\x62lockchain.proto\"\x16\n\x07PingMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x16\n\x07PongMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\'\n\x14\x41\x64\x64ressAdvertisement\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"&\n\x13\x41\x64\x64ressConfirmation\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32q\n\x11\x42lockchainService\x12\x1c\n\x04Ping\x12\x08.PingMsg\x1a\x08.PongMsg\"\x00\x12>\n\radvertiseSelf\x12\x15.AddressAdvertisement\x1a\x14.AddressConfirmation\"\x00\x62\x06proto3'
)




_PINGMSG = _descriptor.Descriptor(
  name='PingMsg',
  full_name='PingMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='PingMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=42,
)


_PONGMSG = _descriptor.Descriptor(
  name='PongMsg',
  full_name='PongMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='PongMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=66,
)


_ADDRESSADVERTISEMENT = _descriptor.Descriptor(
  name='AddressAdvertisement',
  full_name='AddressAdvertisement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='AddressAdvertisement.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=107,
)


_ADDRESSCONFIRMATION = _descriptor.Descriptor(
  name='AddressConfirmation',
  full_name='AddressConfirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='AddressConfirmation.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['PingMsg'] = _PINGMSG
DESCRIPTOR.message_types_by_name['PongMsg'] = _PONGMSG
DESCRIPTOR.message_types_by_name['AddressAdvertisement'] = _ADDRESSADVERTISEMENT
DESCRIPTOR.message_types_by_name['AddressConfirmation'] = _ADDRESSCONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingMsg = _reflection.GeneratedProtocolMessageType('PingMsg', (_message.Message,), {
  'DESCRIPTOR' : _PINGMSG,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:PingMsg)
  })
_sym_db.RegisterMessage(PingMsg)

PongMsg = _reflection.GeneratedProtocolMessageType('PongMsg', (_message.Message,), {
  'DESCRIPTOR' : _PONGMSG,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:PongMsg)
  })
_sym_db.RegisterMessage(PongMsg)

AddressAdvertisement = _reflection.GeneratedProtocolMessageType('AddressAdvertisement', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSADVERTISEMENT,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:AddressAdvertisement)
  })
_sym_db.RegisterMessage(AddressAdvertisement)

AddressConfirmation = _reflection.GeneratedProtocolMessageType('AddressConfirmation', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSCONFIRMATION,
  '__module__' : 'blockchain_pb2'
  # @@protoc_insertion_point(class_scope:AddressConfirmation)
  })
_sym_db.RegisterMessage(AddressConfirmation)



_BLOCKCHAINSERVICE = _descriptor.ServiceDescriptor(
  name='BlockchainService',
  full_name='BlockchainService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=149,
  serialized_end=262,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='BlockchainService.Ping',
    index=0,
    containing_service=None,
    input_type=_PINGMSG,
    output_type=_PONGMSG,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='advertiseSelf',
    full_name='BlockchainService.advertiseSelf',
    index=1,
    containing_service=None,
    input_type=_ADDRESSADVERTISEMENT,
    output_type=_ADDRESSCONFIRMATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOCKCHAINSERVICE)

DESCRIPTOR.services_by_name['BlockchainService'] = _BLOCKCHAINSERVICE

# @@protoc_insertion_point(module_scope)
