# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import blockchain_pb2 as blockchain__pb2


class BlockchainServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/BlockchainService/Ping',
                request_serializer=blockchain__pb2.PingMsg.SerializeToString,
                response_deserializer=blockchain__pb2.PongMsg.FromString,
                )
        self.advertiseSelf = channel.unary_unary(
                '/BlockchainService/advertiseSelf',
                request_serializer=blockchain__pb2.AddressAdvertisement.SerializeToString,
                response_deserializer=blockchain__pb2.AddressConfirmation.FromString,
                )


class BlockchainServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def advertiseSelf(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockchainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=blockchain__pb2.PingMsg.FromString,
                    response_serializer=blockchain__pb2.PongMsg.SerializeToString,
            ),
            'advertiseSelf': grpc.unary_unary_rpc_method_handler(
                    servicer.advertiseSelf,
                    request_deserializer=blockchain__pb2.AddressAdvertisement.FromString,
                    response_serializer=blockchain__pb2.AddressConfirmation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BlockchainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlockchainService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BlockchainService/Ping',
            blockchain__pb2.PingMsg.SerializeToString,
            blockchain__pb2.PongMsg.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def advertiseSelf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BlockchainService/advertiseSelf',
            blockchain__pb2.AddressAdvertisement.SerializeToString,
            blockchain__pb2.AddressConfirmation.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
